git-eternal-move: check $#

diff --git a/refactory/bin/git-eternal-move b/refactory/bin/git-eternal-move
--- a/refactory/bin/git-eternal-move
+++ b/refactory/bin/git-eternal-move
@@ -3,9 +3,12 @@
 # git-eternal-move FROM TO
 #
 set -euf
-git filter-branch --tree-filter "
+if test $# -ne 2; then
+  echo 'Error 1: You are made of stupid!' >&2
+  exit 23
+fi
+exec git filter-branch --tree-filter "
   set -euf
   if test -e '$1'; then
-    mkdir -p '`dirname "$2"`'
     mv '$1' '$2'
   fi"
