update_tinc_hosts: use krebs-conforming errmsgs

diff --git a/modules/retiolum/bin/update_tinc_hosts b/modules/retiolum/bin/update_tinc_hosts
--- a/modules/retiolum/bin/update_tinc_hosts
+++ b/modules/retiolum/bin/update_tinc_hosts
@@ -28,6 +28,6 @@ case "${1-imstupid}" in
     sed -ie "/^$bs$/,/^$es$/d" $hosts 
     ;;
   (*)
-    echo 'You are made of stupid!' >&2
+    echo 'Error 1: You are made of stupid!' >&2
     exit 23
 esac
