fix error message when being connected to the interwebs

diff --git a/usr/lib/autowifi/lib/network b/usr/lib/autowifi/lib/network
--- a/usr/lib/autowifi/lib/network
+++ b/usr/lib/autowifi/lib/network
@@ -7,9 +7,9 @@ check_internet(){
     # TODO determine the loader, either wget or curl
     secret=$(wget -O- http://krebsco.de/secret 2>/dev/null)
     if [ "$secret" == "1337" ]; then
-        echo "cannot load secret or secret incorrect" >&2
         return 0
     else
+        echo "cannot load secret or secret incorrect" >&2
         return 1
     fi
 }
